country: NL
fields:
  - id: first_name
    label: First Name
    type: text
    required: true
    readonly: true
    data_source: nl-user-profile
  - id: last_name
    label: Last Name
    type: text
    required: true
    readonly: true
    data_source: nl-user-profile
  - id: bsn
    label: BSN
    type: text
    required: true
    validation:
      regex: '^\d{9}$'
      message: 'BSN must be 9 digits'
  - id: birth_date
    label: Birth Date
    type: date
    required: true
    readonly: true
    data_source: nl-user-profile
