country: US
fields:
  - id: first_name
    label: First Name
    type: text
    required: true
  - id: last_name
    label: Last Name
    type: text
    required: true
  - id: ssn
    label: SSN
    type: text
    required: true
    validation:
      regex: '^\d{3}-\d{2}-\d{4}$'
      message: 'SSN must be in the format XXX-XX-XXXX'
  - id: birth_date
    label: Birth Date
    type: date
    required: true
